[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "autofluent"
authors = [{name = "plesnja1", email = "plesja1@cvut.cz"}]
dynamic = ["version", "description"]